### ISSUE TITLE
Making angular-ladda work with browserify

### ISSUE THREAD

**Issue by tomteman** [remotty/angular-ladda#21]
angular-ladda doesn't work properly with browserify, since it references the Spinner and Ladda libraries, which are not proper AMD modules (and are also not always used as such in angular-ladda's code).

I have managed to make it work (so I figured I should write it here in case it might help someone else):

- npm install --save browserify-shim

- in your package.json, add the following object:

```javascript
"dependencies": {
    ...
},
"browserify-shim": {

    "ladda": "global:Ladda",

    "spin.js": "global:Spinner"

}
```

 
- require Spinner, Ladda and angular-ladda wherever you usually require external modules (the ordering here is important):

```javascript
window.Spinner = require('/components/ladda/js/spin');
window.Ladda = require('/components/ladda/js/ladda');
require('/components/angular-ladda/dist/angular-ladda');

```

- Simply inject 'angular-ladda' in the relevant module, and that should do it.

```javascript
angular.module('moduleName', [
	'angular-ladda'
])
```

**Comment by radotzki** [comment]
Thanks @tomteman, it works for me.

**Comment by subicura** [comment]
Thank you for guide!!

**Comment by tonestrike** [comment]
@tomteman Do you have an example of this working? I am unable to get it to work unfortunately.
