### ISSUE TITLE
Overwriting global variable "Ladda" ?

### ISSUE THREAD

**Issue by kentcdodds** [remotty/angular-ladda#25]
Note [this line](https://github.com/remotty/angular-ladda/blob/0.2.2/dist/angular-ladda.js#L28) where you assign `root.Ladda` to `factory(root.Ladda)`. But the `factory` doesn't return the `Ladda` object, so you're overriding the `Ladda` global. Doesn't mess me up, because I'm using CommonJS, but I imagine it would throw a bunch of other developers for a loop...

Instead, your `factory` should return the name of the module (like the angular core modules do). For more info, see [this post](https://medium.com/@kentcdodds/e04d4dd58ddc).

**Comment by subicura** [comment]
Thank you for guide! I fix this issue. Please try latest version!

**Comment by kentcdodds** [comment]
I think that fixed it. Thanks!
