### ISSUE TITLE
Order of *.js includes is very important - make a mark in the readme

### ISSUE THREAD

**Issue by RufusJWB** [remotty/angular-ladda#26]
I would like to suggest to make a remark in the readme.md file that the order of the javascript includes is really important. If you include first ladda.js and than spinner.js you will end up with very strange exceptions. Took me two hours to find the problem ;-(

**Comment by Cyruxx** [comment]
Thank you so much! I already doubted myself.

This tip is really important. :+1:

**Comment by subicura** [comment]
Thank you!!
