### ISSUE TITLE
angular-ladda dependancy is missing when using bower install

### ISSUE THREAD

**Issue by michahell** [remotty/angular-ladda#27]
As title says, I've double checked. Because i use grunt bowercopy to copy over only needed files from the bower_components dir, and because I had added the angular-ladda file (apparently bowerCopy does not give an error when copying missing files...huh?) this becomes a very hard bug to detect.

I think that [this issue](https://github.com/remotty/angular-ladda/issues/22) is trying to say the same but it does not really ehm... becomes clear :)

**Comment by subicura** [comment]
@michahell Hello! Can you show me bowercopy config file?

**Comment by e-cloud** [comment]
@michahell , i don't think my issue is on the same topic as yours  as it's focus on the **amd dependencies** stuff but not bower things. Of course, my issue should be closed now as it was fixed.
