### ISSUE TITLE
How to use ladda-themeless.min.css instead of ladda.min.css in my angular project?

### ISSUE THREAD

**Issue by wenxer** [remotty/angular-ladda#30]
hi,

I add angular-ladda to my project and ladda.min.css override bootstrap's default button css. Using ladda-themeless.min.css solving this problem, but I do not know how to configure my angular's gruntfile or bower.json to load the css file.

I use yeoman to setup my project.

Pls help, and thanks a lot.

**Comment by benjamincharity** [comment]
@wenxer you just need to add the correct files to an `overrides` object in your `bower.json`. Then specify the files you want. (You can use this process to use minified vs development files in the same way)

```
{
  "name": "client",
  "version": "0.0.0",
  "dependencies": {
    "ladda": "~0.9.8"
  },
  "overrides": {
      "ladda": {
          "main": [
              "dist/ladda-themeless.min.css"
          ]
      }
  }
}
```

**Comment by fabiowitt** [comment]
Thanks for this answer!
