### ISSUE TITLE
Box visible below button

### ISSUE THREAD

**Issue by floydqwz** [remotty/angular-ladda#32]
For the following code, using angular ladda version 0.3.1:

    <button type="button" class="btn btn-success" data-dismiss="modal" ng-disabled="changeform.$invalid || !valuesChanged()" ng-click="submit()" ladda="loadingStatus.loading" data-style="expand-left">{{'Change' | translate}}</button>

I get an ugly box below the button when I click it. The ladda-spinner appears, but so does the box. (I wasn't quick enough to catch both at the same time though, so in this screen shot you can only see the ugly box):

![angular-ladda](https://cloud.githubusercontent.com/assets/7994792/9517526/e1707c66-4cb0-11e5-9e88-1ff2c7e722cf.png)

**Comment by jonespen** [comment]
I believe this has to do with the way [ladda](http://lab.hakim.se/ladda/) is placing the spinner, and nothing to do with this project. Unfortunately, ladda's issues tracker is closed.

![image](https://cloud.githubusercontent.com/assets/230841/9931159/789500ba-5d39-11e5-91cc-801654738156.png)

**Comment by subicura** [comment]
@floydqwz I also think this is `ladda` library issue. But if you change some css style, it should be resolved. Try add some style your button like `overflow: hidden`.
