### ISSUE TITLE
ladda button style has ploblem  

### ISSUE THREAD

**Issue by avatarr** [remotty/angular-ladda#37]
Hi, I use angular-ladda with boostrap btn class, then I clicked on button function is find but style is not appear like example, see on image below 

![screen shot 2558-10-26 at 14 42 42](https://cloud.githubusercontent.com/assets/1640817/10723763/c4b80138-7bf0-11e5-850b-2362dc013511.png)

**Comment by niner911** [comment]
It looks like you did not include the correct css file. Try to include this - https://github.com/hakimel/Ladda/blob/master/dist/ladda-themeless.min.css

**Comment by avatarr** [comment]
Yes, I can fixed this error. Like you tell me, I use incorrect  a file. 
Thank you.
