### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by kentcdodds** [remotty/angular-ladda#4]
Could you please [publish this to npm](https://gist.github.com/coolaj86/1318304)?

**Comment by kentcdodds** [comment]
Thanks for publishing! Could you please add a `"main"` field to your `package.json` that points to `dist/angular-ladda.js` (this would require adding a build step to copy `angular-ladda` to `dist`. This is better than just pointing to `src/angular-ladda.js` because it gives you the freedom to move your files around without breaking people :-)

**Comment by kentcdodds** [comment]
Just published this. Maybe it'll be helpful :-) [How to distribute your AngularJS module](https://medium.com/@kentcdodds/e04d4dd58ddc)

**Comment by subicura** [comment]
I've add "main" field now!

**Comment by kentcdodds** [comment]
Thanks! :D

**Comment by kentcdodds** [comment]
Could you have it point to a non-minified version of angular-ladda? If I ever need to debug it, the minified version would be really nice.

**Comment by subicura** [comment]
OK, I've change it. check again!

**Comment by kentcdodds** [comment]
@subicura, you're awesome. Thanks for doing this! Is this going to be released so I can start enjoying it?

**Comment by subicura** [comment]
@kentcdodds You're Welcome :)
