### ISSUE TITLE
ladda-text option?

### ISSUE THREAD

**Issue by jonespen** [remotty/angular-ladda#40]
Would have been really cool with a `ladda-text` option, which changes the buttons text to it's value when ladda is active, and back to original text when ladda is not active.

I'll make a pull req.

Btw, great work :100:

**Comment by subicura** [comment]
@jonespen It's great idea. But I think this library should be minimal.(just ladda's angular wrapper)
I think it is better to use angular's default function. How about it?

```
<a class="btn btn-primary" ladda="loader.loading">{{ loader.text }}</a>
```

**Comment by jonespen** [comment]
Sorry, completely forgot about this issue, but thats what i ended up doing :)
