### ISSUE TITLE
use/reference official angular bootstrap bower dependency

### ISSUE THREAD

**Issue by igorlino** [remotty/angular-ladda#42]
Hi I noticed angular-ladda is referencing a pretty old version of angular-bootstrap, which is anyway not referencing the official bower repository (https://github.com/angular-ui/bootstrap-bower)

Instead of using the dependency "angular-bootstrap" it should be using angular-ui-bootstrap-bower"

Cheers

**Comment by subicura** [comment]
@igorlino I change angular-bootstrap dependency version. enjoy!
