### ISSUE TITLE
More Options in laddaProvider ?

### ISSUE THREAD

**Issue by joarhem** [remotty/angular-ladda#43]
Hey, 
very good and easy understandable implementation of the ladda functionalities for angular.

For me (and certainly also for others) it would be great if i could set the spinner color globally in the laddaProvider on module config instead of in every html element. As i saw it, 'style' is the only option available right now, isn't it?

i would like to write my code like:

           laddaProvider.setOption({
                style: 'zoom-out',
                spinnerColor: '#FFB800'
            });

Is this or other option planed to be implemented?

**Comment by subicura** [comment]
@joarhem now, you can use spinnerColor option!

**Comment by joarhem** [comment]
@subicura Awesome thanks :+1:
