### ISSUE TITLE
Inside UI-Bootstrap Modal with animation

### ISSUE THREAD

**Issue by tah182** [remotty/angular-ladda#51]
When the directive is inside an animated view (one that expands or slides) the ladda directive calculates immediately forcing the height and width of the spinner to be 0px. Can we wrap the **link** function in a $timeout so that it can wait until the DOM is loaded?

**Comment by subicura** [comment]
Thanks for reporting issue. I'll check this soon.

**Comment by tah182** [comment]
Hi @subicura , were you able to replicate this? I can create a pull request if needed...

**Comment by subicura** [comment]
Hi @tah182, Can you create a pull request? Thanks!

**Comment by subicura** [comment]
Thank. It's merged!

**Comment by tah182** [comment]
Thank you @subicura ! It looks like the changes were put in a new file in the /src folder, but the main /dist is still unchanged.

**Comment by subicura** [comment]
Sorry @tah182, It's fixed.

**Comment by tah182** [comment]
Hey @subicura. Sorry to keep bothering you. the /dist looks updated. I forgot to compile a min.js for you in my pull request. Can you update that as well? Do you know when you'll cut a new release for bower? Thanks again, Tah
