### ISSUE TITLE
The latest version problem on npm

### ISSUE THREAD

**Issue by nolsherry** [remotty/angular-ladda#53]
Hello @subicura,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
I found the latest version is v0.3.4 on [github](https://github.com/remotty/angular-ladda), but the latest version on [npm](https://www.npmjs.com/package/angular-ladda) is v0.3.3. Could you update the latest version on npm?
Thanks very much!

cdnjs/cdnjs#8420

**Comment by subicura** [comment]
Hello! Thanks for host this library!
I update latest version on npm 0.4.0 now.
