### ISSUE TITLE
Homepage Confirm

### ISSUE THREAD

**Issue by nolsherry** [remotty/angular-ladda#56]
Hello~@subicura, 
I am the member of [cdnjs](https://github.com/cdnjs/) project.
We want to host this library.
Is it the homepage? https://remotty.github.io/angular-ladda/
or it is just a demo page?
thanks!

**Comment by subicura** [comment]
Hi, @nolsherry. It's hompage includes demo. Thanks!

**Comment by nolsherry** [comment]
OK~Thank you for your response.
