### ISSUE TITLE
ladda.remove is not a function

### ISSUE THREAD

**Issue by bdairy** [remotty/angular-ladda#58]
This issue happens when I leave the state

**Comment by bdairy** [comment]
any update

**Comment by subicura** [comment]
@bdairy Hello! Sorry for the late reply.
I think this issue is related to "leave" action. Please show me some example code or route library info.

**Comment by bdairy** [comment]
@subicura This happens on the $destroy scope event..

```
  //scope.$on('$destroy', function () {
                      //    if (ladda) {
                      //        ladda.remove();
                      //    }
                      //});
```
I have normal anuglar-ui router states.. nothing special...I just commented the code to solve it temporarily
