### ISSUE TITLE
"Invalid argument" error on IE11 debugging console

### ISSUE THREAD

**Issue by erinwu** [remotty/angular-ladda#9]
Error "Invalid argument" is generated using IE11 debugging console when the button label is a variable. 

**"Invalid argument" error on IE11 debugging console**
```
<button type="submit" ladda="loading" ng-click="uploadResource()" ng-class="{disabled: uploadBtnDisable}" class="btn btn-success">{{uploadBtnText}}</button>
```

**no error when wrapping within `<span>`**
```
<button type="submit" ladda="loading" ng-click="uploadResource()" ng-class="{disabled: uploadBtnDisable}" class="btn btn-success"><span class="ladda-label">{{uploadBtnText}}</span></button>
```

**no error when the button label is not a variable**
```
<button type="submit" ladda="loading" ng-click="uploadResource()" ng-class="{disabled: uploadBtnDisable}" class="btn btn-success">Add Resource</button>
```

**version of angular and ladda that we are using:**
```				
angular-ladda#0.1.9 app\components\angular-ladda
├── angular#1.3.8
└── ladda#0.9.4
```

**Comment by subicura** [comment]
fix it!

**Comment by erinwu** [comment]
Thank you.

**Comment by chesleybrown** [comment]
Thank you! And Happy New Year! :tada:

**Comment by subicura** [comment]
Happy new year!! :)

**Comment by Zukzuk** [comment]
This problem still persists for me:

![screen shot 2015-01-14 at 10 19 13](https://cloud.githubusercontent.com/assets/329382/5736506/e93b5fdc-9bd6-11e4-8053-c0a3aafe1a0d.png)

And the console error :

![unnamed](https://cloud.githubusercontent.com/assets/329382/5736603/1b97c550-9bd8-11e4-967b-f8b83076ea91.png)

**Comment by chesleybrown** [comment]
Hmm, maybe it's been re-introduced? We are still running `0.1.10` which seems to be okay.

**Comment by Zukzuk** [comment]
I had the same issue in 1.1.10. Forgot to mention

**Comment by subicura** [comment]
@Zukzuk Hi!
I make AngularJS 1.3.8 + angular-ladda 0.1.11 sample.
http://jsfiddle.net/subicura/qomfjL4b/5/
It seems to be fine. I think your problem is special case. Can you make any sample code for that?

**Comment by Zukzuk** [comment]
While debugging I came across the following issue. The ladda doesn't seem to render when a ngIf directive is active on it:

http://jsfiddle.net/Zukzuk/qomfjL4b/9/

Maybe it's a related issue? I do have such a setup in my app.

**Comment by Zukzuk** [comment]
Allright, so I got a little further. The ladda DOES work in a transclude setup with an ngIf:

http://jsfiddle.net/Zukzuk/qomfjL4b/10/

**Comment by Zukzuk** [comment]
The latest update also took care of the error messages in IE. Thanks!

**Comment by subicura** [comment]
Good! Let me know, if you have any trouble!

**Comment by Zukzuk** [comment]
For completeness: This fiddle used to have the IE console error. It is now fixed.

http://jsfiddle.net/Zukzuk/qomfjL4b/32/
